### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [scalgo/scalgo-live-qgis#1]
The functionality described in the About seems already present in core QGIS.
Please clarify what the plugin is actually adding.
Sorry for bothering, but we are trying hard not to duplicate functionality, so to reduce confusion for the users and administrative burden.
Thanks.

**Comment by thomasmoelhave** [comment]
Thanks for you review @pcav, it's much appreciated. I have improved the description in bbcbf7a93549fbea456f4beb7b21028c9571d33d.
Our WMTS servers allow the client to specify an arbitrary real-valued (in most cases) extra parameter to specify particular hydrological events. For instance, the sea-level in a sea-level analysis (see our OpenLayers examples: https://openlayers.org/en/latest/examples/wmts-dimensions.html ). Without this parameter specifying the event it's impossible for our users to add the analysis of interest to their QGIS project. Furthermore the plugin handles authentication and ensures that the right access tokens are sent to our servers. 

It still uses the WMTS stack inside QGIS, it's mostly a question of tweaking the way it's setup and fitting some extra parameters in there.

I have re-uploaded the plugin through the QGIS plugin store.

**Comment by pcav** [comment]
Thanks for the explanation, now published.
Please consider merging your work upstream: adding the possibility of selecting additional parameters could be an useful general improvement to core?
